# Ruff configuration - Relaxed for College Project
target-version = "py311"
line-length = 300

[lint]
# F = Pyflakes (Erros de lógica, variáveis não definidas)
# E = Pycodestyle (Erros de estilo)
select = ["F", "E"]

# Regras que vamos IGNORAR para facilitar a vida:
ignore = [
    "E501", # Linha muito longa (agora aceitamos até 500 chars)
    "I001", # Ordem de importação (não importa mais a ordem)
    "W291", # Espaço no fim da linha (não trava mais)
    "W293", # Espaço em linha em branco (não trava mais)
    "E402", # Imports fora do topo do arquivo (permite imports dentro de funções)
]

exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".venv",
    "projects",
    "tmp",
    "scratch",
    "data"
]
